/* TABLE */
CREATE DATABASE SorDecor
GO

USE SorDecor
GO

CREATE TABLE UserAccounts
(
	ID VARCHAR(128) PRIMARY KEY,
	UserName VARCHAR(50) NOT NULL,
	Pass NVARCHAR(MAX),
	Email NVARCHAR(MAX),
	FirstName NVARCHAR(50),
	LastName NVARCHAR(50) NOT NULL,
	Sex BIT,
	Phone NVARCHAR(20),
	Birthday DATE, 
	Diachi NVARCHAR(MAX),
	STT BIT NOT NULL DEFAULT(1),
)
GO

CREATE TABLE Mades
(
	ID BIGINT IDENTITY(1,1) PRIMARY KEY,
	MadeName NVARCHAR(128) NOT NULL,
	STT BIT NOT NULL DEFAULT(1),
)
GO

CREATE TABLE Categories
(
	ID BIGINT IDENTITY(1,1) PRIMARY KEY,
	CategoryName NVARCHAR(128) NOT NULL,
	STT BIT NOT NULL DEFAULT(1),
)
GO
CREATE TABLE Products
(
	ID VARCHAR(128) PRIMARY KEY,
	ProductName NVARCHAR(MAX) NOT NULL,
	Made BIGINT NOT NULL,
	Info NVARCHAR(MAX),
	Descript NVARCHAR(MAX),
	Price DECIMAL(19,4),
	Sale DECIMAL(19,4) NOT NULL DEFAULT(0),
	Category BIGINT NOT NULL,
	Freeship BIT NOT NULL,
	Image VARBINARY(MAX),
	ImageUrl NVARCHAR(MAX) NOT NULL,
	SL INT NOT NULL DEFAULT(0),
	DateUpdate DATETIME NOT NULL,
	STT BIT NOT NULL DEFAULT(1),

	FOREIGN KEY (Made) REFERENCES Mades(ID),
	FOREIGN KEY (Category) REFERENCES Categories(ID)
)
GO

CREATE TABLE RoleAdmin
(
	ID BIGINT IDENTITY(1,1) PRIMARY KEY,
	RoleName NVARCHAR(128) NOT NULL,
	STT BIT NOT NULL DEFAULT(1)
)
GO

CREATE TABLE Admins
(
	ID NVARCHAR(128) PRIMARY KEY,
	UserName NVARCHAR(128) NOT NULL,
	Pass NVARCHAR(128) NOT NULL,
	NameAd NVARCHAR(MAX) NOT NULL,
	Phone VARCHAR(20),
	RoleAdmin BIGINT NOT NULL,
	STT BIT NOT NULL DEFAULT(1),

	FOREIGN KEY (RoleAdmin) REFERENCES dbo.RoleAdmin(ID)
)
GO

CREATE TABLE Carts
(
	ID VARCHAR(128) PRIMARY KEY,
	UserID VARCHAR(128) NOT NULL,

	FOREIGN KEY (UserID) REFERENCES dbo.UserAccounts(ID)
)
GO

CREATE TABLE ItemInCarts
(
	ID VARCHAR(128) PRIMARY KEY,
	ProductID VARCHAR(128) NOT NULL,
	Price DECIMAL(19,4) NOT NULL,
	SL INT,
	Total DECIMAL(19,4) NOT NULL,
	CartItemID VARCHAR(128) NOT NULL,
	
	
	FOREIGN KEY (ProductID) REFERENCES dbo.Products(ID),
	FOREIGN KEY (CartItemID) REFERENCES dbo.CartS(ID)
)
GO

CREATE TABLE OrderBills
(
	ID VARCHAR(128) PRIMARY KEY,
	UserID VARCHAR(128) NOT NULL,
	UserName NVARCHAR(128) NOT NULL,
	UserAddress NVARCHAR(MAX) NOT NULL,
	Phone VARCHAR(20) NOT NULL,
	Note NVARCHAR(MAX),
	Paid BIT NOT NULL DEFAULT(0),
	DeliverySTT BIT NOT NULL DEFAULT(0),
	DateOrder DATETIME NOT NULL DEFAULT(GETDATE()),
	DeliveryDate DATETIME,
	Email VARCHAR(MAX)

	FOREIGN KEY (UserID) REFERENCES dbo.UserAccounts(ID)
)
GO

CREATE TABLE OrderInfo
(
	ID BIGINT IDENTITY(1,1) PRIMARY KEY,
	ItemOrder VARCHAR(128) NOT NULL,
	ProductID VARCHAR(128) NOT NULL,
	SL INT NOT NULL,
	Total DECIMAL(19,4) NOT NULL,

	FOREIGN KEY (ItemOrder) REFERENCES dbo.OrderBills(ID),
	FOREIGN KEY (ProductID) REFERENCES dbo.Products(ID)
)
GO

CREATE TABLE Feedback
(
	ID BIGINT IDENTITY(1,1) PRIMARY KEY,
	UserID VARCHAR(128) NOT NULL,
	Name NVARCHAR(128) NOT NULL,
	Phone VARCHAR(20) NOT NULL,
	Email NVARCHAR(MAX) NOT NULL,
	Content NVARCHAR(MAX) NOT NULL,
	CreatedDate DATETIME NOT NULL DEFAULT(GETDATE()),
	STT BIT NOT NULL DEFAULT(0),

	FOREIGN KEY (UserID) REFERENCES dbo.UserAccounts(ID)
)
GO